[package]
name = "dragking"
version = "0.2.0"
edition = "2024"
authors = ["Andy Terra <spam@andyterra.com>"]
description = "A very simple implementation of drag and drop for `iced`'s `Row` and `Column` widgets"
license = "MIT"
repository = "https://github.com/airstrike/dragking"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", default-features = false, features = [
    "advanced",
    "wgpu",
    "tokio",
] }

[dev-dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", default-features = false, features = [
    "advanced",
    "lazy",
    "wgpu",
    "tokio",
] }
